### ISSUE TITLE
error when running model.fit

### ISSUE THREAD

**Issue by pongponglau** [miroblog/deep_rl_trader#2]
Thank you so much for this great project.

When i try to run ddqn_rl_trader.py on windows (my computer has no GPU, so i use LSTM instead of CuDNNLSTM), i get the following errors:

2019-01-17 17:06:16.101245: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary
start episode ... XBTUSD_5m_70000_train.csv at 0
Traceback (most recent call last):
  File "ddqn_rl_trader.py", line 81, in <module>
    main()
  File "ddqn_rl_trader.py", line 65, in main
    dqn.fit(env, nb_steps=5500, nb_max_episode_steps=10000, visualize=False, verbose=0)
  File "C:\Python36\lib\site-packages\rl\core.py", line 182, in fit
    if not np.isreal(value):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

May i ask what change i can make to this problem?

Thanks a lot

**Comment by Jack30e** [comment]
I'm having the same error... has anyone a solution?

**Comment by ghost** [comment]
@miroblog I am having the same issue. Do you have an idea?

> (Pdb) dqn.fit(env, nb_steps=5500, nb_max_episode_steps=10000, visualize=False, verbose=2)
> Training for 5500 steps ...
> start episode ... XBTUSD_5m_70000_train.csv at 0
> *** ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or 

```
ENV_NAME = 'OHLCV-v0'
TIME_STEP = 30
PATH_TRAIN = "./data/train/"
PATH_TEST = "./data/test/"
env = OhlcvEnv(TIME_STEP, path=PATH_TRAIN)
env_test = OhlcvEnv(TIME_STEP, path=PATH_TEST)

def create_model(shape, nb_actions):
    model = Sequential()
    model.add(LSTM(64, input_shape=shape, return_sequences=True))
    model.add(LSTM(64))
    model.add(Dense(32))
    model.add(Activation('relu'))
    model.add(Dense(nb_actions, activation='linear'))
    return model
np.random.seed(123)
env.seed(123)

# create_model
nb_actions = env.action_space.n
model = create_model(shape=env.shape, nb_actions=nb_actions)
print(model.summary())

# create memory
memory = SequentialMemory(limit=50000, window_length=TIME_STEP)

# create policy
policy = EpsGreedyQPolicy()# policy = BoltzmannQPolicy()

# create agent
# you can specify the dueling_type to one of {'avg','max','naive'}

dqn = DQNAgent(model=model, nb_actions=nb_actions, memory=memory, nb_steps_warmup=200,  enable_dueling_network=True, dueling_type='avg', target_model_update=1e-2, policy=policy, processor=NormalizerProcessor())
dqn.compile(Adam(lr=1e-3), metrics=['mae'])

while True:
    # train
    pdb.set_trace()
    dqn.fit(env, nb_steps=5500, nb_max_episode_steps=10000, visualize=False, verbose=2)
```

**Comment by GenesisGupta** [comment]
pls change the file of C:\Python36\lib\site-packages\rl\core.py with the core.py file given here : deep_rl_trader/modified_keras_rl_core/

let me know in case you are facing any problems.

if somebody is wishing to collaborate on this , i am willing to collaborate

**Comment by canercak** [comment]
@GenesisGupta it works now, thank you. I am willing to colloborate in creating a binance trading bot with backtest and live trading that continuously trains on Open AI Gym. Could not see your contributions, are you the owner of the project?

**Comment by GenesisGupta** [comment]
Hi,

I am not the owner of this project , but looking at creating a bot that can
trade on itself.

I also trade crypto currencies using systematic trading models.

Regards,
Nitin Gupta
9731423808

**Comment by canercak** [comment]
@GenesisGupta Is that a phone number? you can send me msg canercak@gmail.com or add me on telegram "canercak". 
Me too traded manually and automatically with indicators and with my renko ruby bot, gekko, freqtrade, etc and got into ML because they don't work.
Do you think we can make that bot from this project?  this project uses Duel Deep Q Network Agent with keras-rl. For the last last 3 months day and night I've been experimenting with almost all python machine learning projects geared for stock predictions and done some of my own LSTM's...dqn/ddqn seem to give results. Also Keras-rl backend is the easiest to understand/use. Compared to gym_trading repo by aDrian Portabales and many others I've checked, this project also seems to earn money(rewards). However I could not check it with CuDNNLSTM since I don't have GPU( do you have one?) also I still cannot exactly figure out the way to use the timesteps right in backtesting/live trading. I am also not much experienced in python and ml, are you experienced?

**Comment by raghavb** [comment]
Hey, how did you guys install all the requirements? There are so many versions of dependencies that are not available. Any help would be highly appreciated. Thanks!

**Comment by ghost** [comment]
install in conda env, try installing the ones that don't work by removing the version tag

**Comment by netvienna** [comment]
> pls change the file of C:\Python36\lib\site-packages\rl\core.py with the core.py file given here : deep_rl_trader/modified_keras_rl_core/
> 
> let me know in case you are facing any problems.
> 
> if somebody is wishing to collaborate on this , i am willing to collaborate

thx. On linux got to your environment folder 
/home/username.../anaconda3/envs/bt4ker/lib/python3.6/site-packages/rl/
and replace it. Then it works.
Thx for the hint.
